"""VAJRA step 2 — Piṅgala's laghu/guru binary, implemented for real.

Piṅgala's *Chandaḥśāstra* (c. 3rd century BCE) enumerates poetic metres by
treating each syllable as **laghu (लघु, light)** or **guru (गुरु, heavy)** — a
two-symbol alphabet, i.e. a binary system roughly two millennia before Leibniz.
This module implements the parts that are genuinely algorithmic:

* **prastāra** — the full enumeration of patterns for a metre of ``k`` syllables,
  in the traditional order (all-guru first);
* **naṣṭam** — given a position in that enumeration, recover the pattern (the
  halving algorithm the tradition describes);
* **uddhiṣṭam** — the inverse: the position of a known pattern;
* **meru** — the binomial triangle, whose rows count patterns by number of gurus,
  checked here against :func:`math.comb`;
* **prosody** — real syllable weights computed from a Devanagari/IAST line by the
  ordinary rules (long vowel, conjunct, anusvāra/visarga → guru), so the binary
  is derived from actual sound rather than invented.

And the honest framing, which is the point of putting this in a *security* tree:
a laghu/guru pattern is a **public, invertible encoding**, not a cipher. Nobody
needs to know Piṅgala to invert it — the mapping between bits and light/heavy
syllables is right here in this file. See :func:`confidentiality_report`.

    >>> from aegis.vajra.chandas_binary import nastam, uddistam
    >>> nastam(2, 3)
    'GGL'
    >>> uddistam("GGL")
    2
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from .paninian_grammar import VOWELS, to_devanagari

__all__ = [
    "LAGHU",
    "GURU",
    "prastara",
    "nastam",
    "uddistam",
    "meru",
    "meru_row_sum",
    "weigh_aksaras",
    "pattern_to_bits",
    "bits_to_pattern",
    "encode_bytes",
    "decode_bytes",
    "metre_of",
    "METRES",
    "confidentiality_report",
]

LAGHU = 0
GURU = 1

_SYMBOLS = {LAGHU: "L", GURU: "G"}
_DEVA = {LAGHU: "ल", GURU: "ग"}

#: Quarterly syllable counts of the common metres (pāda = quarter).
METRES: Dict[str, int] = {
    "āryā": 30,          # not strictly 4×, kept for naming only
    "anuṣṭubh": 8,
    "gāyatrī": 8,
    "triṣṭubh": 11,
    "jagatī": 12,
    "virāṭ": 14,
    "bhujaṅgaprayāta": 12,
}

_LONG_VOWELS = {"ā", "ī", "ū", "ṝ", "e", "ai", "o", "au"}


# ---------------------------------------------------------------------------
# The enumeration itself
# ---------------------------------------------------------------------------
def prastara(syllables: int) -> List[str]:
    """Every pattern of ``syllables`` light/heavy positions, all-guru first.

    This is Piṅgala's prastāra: 2**syllables rows, generated by the same
    doubling he describes (each row of the previous prastāra appears twice,
    prefixed first with guru then with laghu).
    """
    if syllables < 0 or syllables > 20:
        raise ValueError("syllables must be between 0 and 20")
    rows = [""]
    for _ in range(syllables):
        rows = ["G" + row for row in rows] + ["L" + row for row in rows]
    return rows


def nastam(index: int, syllables: int) -> str:
    """The pattern at position ``index`` (1-based) in the prastāra.

    The classical halving algorithm: the index is repeatedly halved, and the
    remainder decides the syllable. Guru counts as 1, laghu as 0.
    """
    if not 1 <= index <= 2 ** syllables:
        raise ValueError(f"index must be between 1 and {2 ** syllables}")
    value = index - 1
    bits = [(value >> shift) & 1 for shift in range(syllables - 1, -1, -1)]
    # In Pingala's ordering the *complement* of the binary form is written,
    # because the enumeration starts from all-guru, not from zero.
    return "".join(_SYMBOLS[GURU if bit == 0 else LAGHU] for bit in bits)


def uddistam(pattern: str) -> int:
    """The 1-based position of ``pattern`` in the prastāra (inverse of nastam)."""
    value = 0
    for symbol in pattern:
        if symbol.upper() not in {"L", "G"}:
            raise ValueError(f"unexpected symbol {symbol!r}; expected 'L' or 'G'")
        value = (value << 1) | (0 if symbol.upper() == "G" else 1)
    return value + 1


def meru(rows: int) -> List[List[int]]:
    """Piṅgala's meru: row ``k`` counts patterns with 0..k gurus."""
    if rows < 0:
        raise ValueError("rows must be non-negative")
    triangle: List[List[int]] = []
    for row in range(rows):
        triangle.append([math.comb(row, index) for index in range(row + 1)])
    return triangle


def meru_row_sum(row: int) -> int:
    """The sum of meru row ``k`` must be 2**k — the prastāra size."""
    return sum(meru(row + 1)[row])


# ---------------------------------------------------------------------------
# Prosody
# ---------------------------------------------------------------------------
def _aksaras(iast: str) -> List[str]:
    """Split an IAST string into syllables (a crude but deterministic akshara splitter)."""
    vowels = sorted(VOWELS, key=len, reverse=True)
    syllables: List[str] = []
    current = ""
    index = 0
    while index < len(iast):
        character = iast[index]
        if character in {" ", "-", "।", "|"}:
            if current:
                syllables.append(current)
                current = ""
            index += 1
            continue
        vowel = next((v for v in vowels if iast.startswith(v, index)), None)
        if vowel:
            current += vowel
            index += len(vowel)
            # Everything up to the next vowel belongs to this syllable.
            while index < len(iast):
                next_vowel = next((v for v in vowels if iast.startswith(v, index)), None)
                if next_vowel or iast[index] in {" ", "-", "।", "|"}:
                    break
                current += iast[index]
                index += 1
            syllables.append(current)
            current = ""
            continue
        current += character
        index += 1
    if current:
        syllables.append(current)
    return syllables


def weigh_aksaras(iast: str) -> List[int]:
    """Weigh syllables of an IAST line: 1 (guru) or 0 (laghu).

    The ordinary rules: a long vowel is heavy; a short vowel followed by two or
    more consonants (a conjunct) is heavy by position; a short vowel before
    anusvāra or visarga is heavy; otherwise light. The last syllable of a pāda is
    conventionally heavy, which callers can apply themselves.
    """
    weights: List[int] = []
    for aksara in _aksaras(iast):
        vowel = next((v for v in sorted(VOWELS, key=len, reverse=True) if v in aksara), "a")
        tail = aksara[aksara.index(vowel) + len(vowel) :]
        heavy = vowel in _LONG_VOWELS
        if not heavy and len([character for character in tail if character not in "ṃḥ"]) >= 2:
            heavy = True  # conjunct after a short vowel
        if "ṃ" in tail or "ḥ" in tail:
            heavy = True
        weights.append(GURU if heavy else LAGHU)
    return weights


def pattern_to_bits(pattern: str) -> str:
    """``"GGL"`` -> ``"110"`` (guru = 1, laghu = 0, the brief's convention)."""
    return "".join("1" if symbol.upper() == "G" else "0" for symbol in pattern)


def bits_to_pattern(bits: str) -> str:
    """``"110"`` -> ``"GGL"``. Accepts the other convention via ``invert=True``."""
    return "".join("G" if bit == "1" else "L" for bit in bits)


def encode_bytes(data: bytes, *, syllables: int = 8) -> str:
    """Encode bytes as a sequence of prastāra rows written in Devanagari letters.

    This is what "convert all data to the Vedic binary" can mean concretely: a
    fixed, reversible mapping from bits to light/heavy syllables. Reversible, and
    emphatically not secret.
    """
    bits = "".join(f"{byte:08b}" for byte in data)
    rows: List[str] = []
    for offset in range(0, len(bits), syllables):
        chunk = bits[offset : offset + syllables].ljust(syllables, "0")
        rows.append(bits_to_pattern(chunk))
    return " ".join("".join(_DEVA[GURU if s == "G" else LAGHU] for s in row) for row in rows)


def decode_bytes(text: str, *, syllables: int = 8) -> bytes:
    """Inverse of :func:`encode_bytes`.

    ``syllables`` must match the encoder, because padding to the metre boundary
    is the only information the encoding adds; a shared value is part of the
    wire format, not a secret.
    """
    letters = [character for character in text if character in {"ल", "ग"}]
    bits = "".join("1" if character == "ग" else "0" for character in letters)
    whole = len(bits) - (len(bits) % syllables)
    bits = bits[:whole]
    return bytes(int(bits[offset : offset + 8], 2) for offset in range(0, len(bits) - len(bits) % 8, 8))


def metre_of(pattern: str) -> Optional[str]:
    """Name the metre whose pāda length matches ``pattern``, if any."""
    length = len(pattern.replace(" ", ""))
    for name, syllables in METRES.items():
        if syllables == length:
            return name
    return None


def confidentiality_report(sample: bytes = b"@LOC[TYO] -> ?WX") -> Dict[str, Any]:
    """Measure this module's own (lack of) confidentiality, rather than claim it.

    The brief describes the Chandas step as part of an "impenetrable fortress".
    It is a published encoding with a fixed table, so the useful thing this
    module can do is *demonstrate* how quickly it falls over.
    """
    import time

    encoded = encode_bytes(sample)
    started = time.perf_counter()
    recovered = decode_bytes(encoded)
    elapsed_ms = (time.perf_counter() - started) * 1000.0
    return {
        "is_encryption": False,
        "requires_a_key": False,
        "decoded_without_any_secret": recovered == sample,
        "decode_time_ms": round(elapsed_ms, 4),
        "how_to_break": "read chandas_binary.py; the table is right there",
        "what_it_is_good_for": "a stable, reversible numeric representation of a payload — nothing more",
    }
